import LocalizedStrings from 'react-native-localization';

export const strings = new LocalizedStrings({
  ba: {
    google_login_title: 'Prijavi se putem Googla',
    sms_login_title: 'Prijavi se putem SMS-a',
    email_login_title: 'Prijavi se putem e-maila',
    register_via_email: 'Registruj se putem e-maila',
    terms_of_use_part1: 'Korištenjem aplikacije prihvatate ',
    terms_of_use_part2: 'Uslove korištenja',
    welcome: 'Dobrodošli',
    discount_title: 'Popusti i do 50%',
    total: 'Ukupno',
    points: 'bodova',
    my_account: 'Moj račun',
    coupons: 'Kuponi',
    transactions: 'Transakcije',
    notifications: 'Notifikacije',
    survey: 'Anketa',
    about_us: 'O nama',
    settings: 'Postavke',
    logout: 'Odjava',
    facebook: 'Facebook',
    google: 'Google',
    twitter: 'Twitter',
    instagram: 'Instagram',
    linkedin: 'LinkedIn',
    website: 'Website',
    unfinished: 'Nedovršeno',
    featured_categories: 'Izdvojene kategorije',
    see_all: 'Pogledaj sve',
    active_coupons: 'Aktivni kuponi',
    categories: 'Kategorije',
    no_data: 'Nema podataka',
  },
});
